name: test and build

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'example/**'
      - 'test/**'
      - 'build/**'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
